SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Creating [dbo].[WebinarAttendees]'
GO
CREATE TABLE [dbo].[WebinarAttendees]
(
[name] [varchar] (255) NULL
)
GO

