name: Flyway-Check

on:
  pull_request:
    branches:
      - main
env:
  FLYWAY_EMAIL: "${{ secrets.FLYWAY_EMAIL }}" # Enter the email address linked to the Redgate Account that created the PAT
  FLYWAY_TOKEN: "${{ secrets.FLYWAY_TOKEN }}" # Enter the PAT Value (This should be treated like a password and thus as a secure variable.

jobs:
  check:
    name: Flyway Check
    runs-on: "self-hosted" # (https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners)
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # Step 1 - Flyway License Authentication
      - name: Flyway Authentication
        run: flyway auth -IAgreeToTheEula -email="${{ env.FLYWAY_EMAIL }}" -token="${{ env.FLYWAY_TOKEN }}"
      
      # Step 2 - Create Check Report 
      - name: Create Check Reports
        run: flyway check -code -environment="Prod" -"check.code.failOnError=true" -configFiles="${{ GITHUB.WORKSPACE }}\flyway.toml" -locations="filesystem:${{ GITHUB.WORKSPACE }}\migrations" "-reportFilename=${{ GITHUB.WORKSPACE }}\reports\AutoPilotProd-Run-${{ GITHUB.RUN_ID }}-Prod-Check-Report.html" 
      
      # Step 3 - Publish Check Report
      - name: Publish Check Report as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with: 
          name: flyway-reports-prod
          path: ${{ GITHUB.WORKSPACE }}\reports\AutoPilotProd-Run-${{ GITHUB.RUN_ID }}-Prod-Check-Report.html
          
