name: Flyway-Check

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: self-hosted
    env:
      WORKING_DIRECTORY: ${{ github.workspace }}
      FLYWAY_ENV_NATIVE_SQLFLUFF: true

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/download-artifact@v4
        with:
          name: flyway-build-artifact-${{ github.run_number }}
     
       # Step 1 - Flyway License Authentication #
      - name: Flyway Authentication
        run: flyway auth -IAgreeToTheEula -email="${{ env.FLYWAY_EMAIL }}" -token="${{ env.FLYWAY_TOKEN }}"
      
      # Step 2 - Create Check Report 
      - name: Create Check Reports
        run: flyway check -environment="Prod" -"check.failOnDrift=true" -configFiles="${{ GITHUB.WORKSPACE }}\flyway.toml" -locations="filesystem:${{ GITHUB.WORKSPACE }}\migrations" "-reportFilename=${{ GITHUB.WORKSPACE }}\reports\AutoPilotProd-Run-${{ GITHUB.RUN_ID }}-Prod-Check-Report.html" 
      
      # Step 3 - Publish Check Report
      - name: Publish Check Report as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with: 
          name: flyway-reports-prod
          path: ${{ GITHUB.WORKSPACE }}\reports\AutoPilotProd-Run-${{ GITHUB.RUN_ID }}-Prod-Check-Report.html
          
